spring:
  profiles:
    include: oauth
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    generate-unique-name: false
    username: sa
  session:
    store-type: jdbc
server:
  servlet:
    encoding:
      force-response: true
