spring:
  config:
    location:
      - classpath:application-real.yml
      - classpath:application-oauth.yml
  jpa:
    show_sql: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    generate-unique-name: false
    username: sa
  session:
    store-type: jdbc
server:
  servlet:
    encoding:
      force-response: true
